soundscapes:
  _target_: src.pl_modules.module.SoundscapeDetection

birdcalls:
  _target_: src.pl_modules.module.BirdcallClassification
  out_features: 397 # Number of bird classes.

joint:
  _target_: src.pl_modules.module.JointClassification
  out_features: 398 # Number of bird classes + nocall.

